// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKEzHQP3WLrKRuideVeEq-hMBL03kPOoo',
    appId: '1:681970183730:web:a9d2e39369b054382fd62b',
    messagingSenderId: '681970183730',
    projectId: 'crud-7187e',
    authDomain: 'crud-7187e.firebaseapp.com',
    storageBucket: 'crud-7187e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAexs-zq5g1RiWidagHdQhNKvyuTap1nTY',
    appId: '1:681970183730:android:238dc0bab8439b6d2fd62b',
    messagingSenderId: '681970183730',
    projectId: 'crud-7187e',
    storageBucket: 'crud-7187e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5YPn6gpZz7tZ7pGlVEnffo2fr0keRL8o',
    appId: '1:681970183730:ios:73a2f88d4c2c72eb2fd62b',
    messagingSenderId: '681970183730',
    projectId: 'crud-7187e',
    storageBucket: 'crud-7187e.appspot.com',
    iosBundleId: 'com.example.noteapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5YPn6gpZz7tZ7pGlVEnffo2fr0keRL8o',
    appId: '1:681970183730:ios:73a2f88d4c2c72eb2fd62b',
    messagingSenderId: '681970183730',
    projectId: 'crud-7187e',
    storageBucket: 'crud-7187e.appspot.com',
    iosBundleId: 'com.example.noteapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKEzHQP3WLrKRuideVeEq-hMBL03kPOoo',
    appId: '1:681970183730:web:9eb9410c0a9a45b62fd62b',
    messagingSenderId: '681970183730',
    projectId: 'crud-7187e',
    authDomain: 'crud-7187e.firebaseapp.com',
    storageBucket: 'crud-7187e.appspot.com',
  );
}
